# Generated by Django 5.1.3 on 2024-11-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room_book', 'check_in', 'check_out')},
        ),
    ]
